"""add_pts_qts_access_hash

Revision ID: f6557dcaaaa3
Revises: 006
Create Date: 2026-07-09 19:08:26.925022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6557dcaaaa3'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('pts', sa.BigInteger(), nullable=True))
    op.add_column('telegram_accounts', sa.Column('qts', sa.BigInteger(), nullable=True))
    op.add_column('telegram_accounts', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_chats', sa.Column('access_hash', sa.BigInteger(), nullable=True))
    
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'telegram_chat_id' not in columns:
        op.add_column('users', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
        op.create_unique_constraint(None, 'users', ['telegram_chat_id'])
        
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'telegram_chat_id' in columns:
        op.drop_constraint(None, 'users', type_='unique')
        op.drop_column('users', 'telegram_chat_id')
        
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('telegram_chats', 'access_hash')
    op.drop_column('telegram_accounts', 'date')
    op.drop_column('telegram_accounts', 'qts')
    op.drop_column('telegram_accounts', 'pts')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
